services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: chatbot-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env   # 👈 ahora leerá tu API key desde backend/.env
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: chatbot-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000
    restart: always
